# Generated by Django 4.2.6 on 2023-10-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_content_manager',
            field=models.BooleanField(default=False, verbose_name='контент-менеджер'),
        ),
    ]
