# Generated by Django 4.2.6 on 2023-10-29 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_alter_mailing_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='log',
        ),
        migrations.AddField(
            model_name='log',
            name='creation_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='log',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='рассылка'),
        ),
        migrations.AlterField(
            model_name='log',
            name='attempt_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата и время последней попытки'),
        ),
        migrations.AlterField(
            model_name='log',
            name='attempt_status',
            field=models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Не удалось отправить'), ('pending', 'В ожидании')], default='pending', max_length=10, verbose_name='статус попытки'),
        ),
        migrations.AlterField(
            model_name='log',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера'),
        ),
    ]
