# Generated by Django 4.2.6 on 2023-10-30 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0011_remove_mailing_log_log_creation_time_log_mailing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cоздатель'),
        ),
        migrations.AddField(
            model_name='message',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cоздатель'),
        ),
    ]
